name: Build
on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: einkvnc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: arm-unknown-linux-musleabihf
    - name: Install Cross
      run: cargo install cross
    - name: Build Client
      run: |
        cd client
        export CARGO_BUILD_TARGET=arm-unknown-linux-musleabihf
        cross test
        cross build --release
    - name: Upload release archive
      uses: actions/upload-artifact@v4
      with:
        name: eInkVnc
        path: client/target/arm-unknown-linux-musleabihf/release/einkvnc
    - name: Build Emulator
      run: |
        sudo apt install -y libsdl2-dev libevdev-dev
        cd emulator
        cargo build
