name: Build
on: [push, pull_request,workflow_dispatch]

jobs:
  build_fbink:
    name: einkvnc
    runs-on: ubuntu-latest
    steps:
    - name: Show GLIBC
      run: ldd --version
    - name: Linker
      run: sudo apt-get -y install libstdc++-11-dev-armhf-cross build-essential autoconf automake bison flex gawk libtool libtool-bin libncurses-dev curl file git gperf help2man texinfo unzip wget
    - name: Download toolchain
      run: wget -q https://github.com/koreader/koxtoolchain/releases/latest/download/kobo.tar.gz -O - | tar -xzf - -C ~
    - name: Export toolchain
      run: echo "$HOME/x-tools/arm-kobo-linux-gnueabihf/bin" >> $GITHUB_PATH && ls -la $HOME/x-tools/arm-kobo-linux-gnueabihf/bin && $HOME/x-tools/arm-kobo-linux-gnueabihf/bin/arm-kobo-linux-gnueabihf-gcc --version
    - name: Show GLIBC and Linker
      run: echo $PATH && ls -la $HOME/x-tools/arm-kobo-linux-gnueabihf/bin/ && $HOME/x-tools/arm-kobo-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc --version && ldd --version && arm-linux-gnueabihf-gcc --version
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: arm-unknown-linux-gnueabihf
    - name: Build
      run: PATH=~/x-tools/arm-kobo-linux-gnueabihf/bin:$PATH && cd client && ./build.sh
    - name: Upload release archive
      uses: actions/upload-artifact@v4
      with:
        name: eInkVnc
        path: client/target/arm-unknown-linux-gnueabihf/release/einkvnc*
